remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: George Michael Taborda Garces
submodulo: python 
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/python-9283f.appspot.com/o/313401598_10229180404031003_2870453652358549738_n.jpg?alt=media&token=b5f9ccbc-99e2-452b-b652-464811f186c4

