remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: George Michael Taborda Garces
submodulo: python 
periodo: 2023-2
url_foto: https://www.facebook.com/photo/?fbid=10229180404071004&set=a.1618215451587

